"""add client table

Revision ID: 6f9d4e4f1308
Revises: 1fb239e1e038
Create Date: 2026-05-13 16:36:57.713341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9d4e4f1308'
down_revision: Union[str, Sequence[str], None] = '1fb239e1e038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=False),
    sa.Column('hmac_secret', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_api_key'), 'clients', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_api_key'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
